const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const TRIPPLE_INCREMENT = "TRIPPLE_INCREMENT";
const TRIPPLE_DECREMENT = "TRIPPLE_DECREMENT";
const RESET = "RESET";
const FETCH_SUCCESS = "FETCH_SUCCESS";
const FETCH_FAILED = "FETCH_FAILED";
const GET_ALL_POST = "GET_ALL_POST";

export {
  INCREMENT,
  DECREMENT,
  TRIPPLE_INCREMENT,
  TRIPPLE_DECREMENT,
  RESET,
  FETCH_SUCCESS,
  FETCH_FAILED,
  GET_ALL_POST,
};
